<?xml version="1.0" encoding="UTF-8"?>

<!-- ## Ejercicio 2 â€” Equipo PokÃ©mon (cardinalidades)
**Objetivo:** Usar `+` y `*`.  

ðŸ“Œ Instrucciones:  
1. Crea un XML con DTD interna que represente un **equipo PokÃ©mon**.  
2. El elemento raÃ­z serÃ¡ `<equipo>`.  
3. Reglas de DTD:  
   - `equipo` contiene **uno o mÃ¡s** `pokemon` (`pokemon+`).  
    - `pokemon` contiene: `pokemon`, `tipo`, `nivel?`.  
   - `tipo` puede repetirse **una o mÃ¡s veces** (`tipo+`) porque un PokÃ©mon puede tener varios tipos
(ej. Agua + Volador).   -->


<!DOCTYPE equipo [
    <!ELEMENT equipo (pokemon+)>
    <!ELEMENT pokemon (nombre, tipo+, nivel?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT nivel (#PCDATA)>
]>

<equipo>
    <pokemon>
        <nombre>Charizard</nombre>
        <tipo>Fuego</tipo>
        <tipo>Volador</tipo>
        <nivel>12</nivel>
    </pokemon>
</equipo>