=== castilloubedaruben/Apuntes-1-DAW/Lenguajes-Marcas-Ruben/Relacion4 XSD/ejercicio4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clase">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-zA-Z ]*" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="6" />
                                        <xs:maxInclusive value="18" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(\d{8}[A-Z])"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="notas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nota" minOccurs="1" maxOccurs="5">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0" />
                                                    <xs:maxInclusive value="10" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

<!-- Ejercicio 4 â€“ Alumnos y Notas
DiseÃ±a desde cero un XML y su XSD para un sistema escolar con estas caracterÃ­sticas:

El documento tiene un elemento raÃ­z clase.
La clase contiene varios alumno.
Cada alumno tiene:
nombre (cadena que debe empezar con mayÃºscula, regex).
edad (entero entre 6 y 18).
Una lista de nota (decimal entre 0 y 10, puede haber entre 1 y 5 notas).
Un dni que siga el formato 8 dÃ­gitos + 1 letra (regex).
El alumno debe tener un atributo id Ãºnico (entero positivo).
ðŸ‘‰ Tu tarea:

Define el XSD.
Escribe un XML con al menos 2 alumnos y sus notas. -->

=== castilloubedaruben/Apuntes-1-DAW/Lenguajes-Marcas-Ruben/Relacion4 XSD/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<clase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio4.xsd">
    <alumno id="1">
        <nombre>Ruben</nombre>
        <edad>18</edad>
        <dni>75571171W</dni>
        <notas>
            <nota>8.5</nota>
            <nota>7.5</nota>
            <nota>5</nota>
        </notas>
    </alumno>
    <alumno id="2">
        <nombre>Antonio</nombre>
        <edad>17</edad>
        <dni>75582171Q</dni>
        <notas>
            <nota>9</nota>
            <nota>6.5</nota>
            <nota>5</nota>
        </notas>
    </alumno>
</clase>

<!-- Ejercicio 4 â€“ Alumnos y Notas
DiseÃ±a desde cero un XML y su XSD para un sistema escolar con estas caracterÃ­sticas:

El documento tiene un elemento raÃ­z clase.
La clase contiene varios alumno.
Cada alumno tiene:
nombre (cadena que debe empezar con mayÃºscula, regex).
edad (entero entre 6 y 18).
Una lista de nota (decimal entre 0 y 10, puede haber entre 1 y 5 notas).
Un dni que siga el formato 8 dÃ­gitos + 1 letra (regex).
El alumno debe tener un atributo id Ãºnico (entero positivo).
ðŸ‘‰ Tu tarea:

Define el XSD.
Escribe un XML con al menos 2 alumnos y sus notas. -->
